### PR TITLE
[Patch]: Sapphire framework v1.0.1

### PR DESCRIPTION
**Pull request by tintinkung**
### Changes: 

- moves regex prefixes to config.json and naming changes to the config
- Smarter regex prefixes in config.json
  > ex. 
  >  - hey bot `<command>`
  > - hey merlion pls `<command>`
  > - oi bot pls gib `<command>`
- edit some conflict test command _(owner only)_

### New Feature:

uwuify command uwu

### CODE REVIEW

**Review by Kira272921 — APPROVED** [review]
Great work 👍(*Typical code approves*)

**Comment by tintinkung** [comment]
@StoneMcYT plz approve uwu

**Comment by tintinkung** [comment]
[Review PR https://github.com/ASEAN-Build-The-Earth/Merlion/pull/80](https://trello.com/c/XdBoRcqu/7-review-pr-https-githubcom-asean-build-the-earth-merlion-pull-80)

**Review by StoneMcYT — COMMENTED** [review]
Have not done a full reveiw yet gotta read a bit on the uwuifier npm module

**Review by StoneMcYT — APPROVED** [review]
GO MERGE

**Comment by tintinkung** [comment]
> GO MERGE

GO DEPLOY

**Pull request merged**
